/** Resolve generated CloudFormation templates (CDK synth → infra/*.yaml). */

import { existsSync } from "node:fs";
import { join } from "node:path";
import { INFRA_TEMPLATE, type InfraTemplateKindValue } from "./constants.js";

export type InfraTemplateKind = InfraTemplateKindValue;

/**
 * Prefer repo `infra/{kind}.yaml`, then MEMSTREAM_ROOT / prebuilt `/opt/memstream`.
 * Templates are generated by `npm run synth -w @memstream/infra` (source: infra/cdk).
 */
export function infraTemplatePath(
  root: string,
  kind: InfraTemplateKind,
): string {
  const name =
    kind === INFRA_TEMPLATE.EC2 ? "ec2.yaml" : "lambda.yaml";
  const paths = [
    join(root, "infra", name),
    ...(process.env.MEMSTREAM_ROOT?.trim()
      ? [join(process.env.MEMSTREAM_ROOT.trim(), "infra", name)]
      : []),
    `/opt/memstream/infra/${name}`,
  ];
  const found = paths.find((p) => existsSync(p));
  if (!found) {
    throw new Error(
      `Missing template ${join(root, "infra", name)} ` +
        `(run: npm run synth:infra). Also checked MEMSTREAM_ROOT / /opt/memstream.`,
    );
  }
  return found;
}
