#!/usr/bin/env node
/**
 * Embed sql/*.sql into packages/engine/src/embedded-schema.ts so runtime
 * (EC2 standalone / Lambda) can apply schema without a repo checkout.
 * Source of truth remains sql/ — run `make setup-db` for explicit migrations.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "../../.."); // packages/engine/scripts → repo root
const out = join(here, "../src/embedded-schema.ts");

const files = {
  MEMSTREAM_SCHEMA_SQL: "sql/memstream.sql",
  APPLICATION_SCHEMA_SQL: "sql/application.sql",
};

const parts = [
  "/** Generated by scripts/embed-schema.mjs — do not edit. Source: sql/*.sql */",
  "",
];

for (const [name, rel] of Object.entries(files)) {
  const body = readFileSync(join(root, rel), "utf8");
  parts.push(`export const ${name} = ${JSON.stringify(body)} as const;`, "");
}

writeFileSync(out, parts.join("\n"));
console.error(`embedded-schema.ts ← ${Object.values(files).join(", ")}`);
